TARGET = recive.exe
LDFLAGS = -mwindows
LIBS_PATH = ../libs
LIBS_NAME = ws2_32 winmm mapi32 imm32 winspool comctl32 comdlg32 gdi32 ole32 user32 uuid getPcMsgApi wininet
SRC_PATH =  .
C_PATH = $(SRC_PATH)
CPP_PATH = $(SRC_PATH)

include ../include.mk