TARGET = service.exe
LDFLAGS = -mwindows
INC_PATH = ../include
LIBS_PATH = ../libs
LIBS_NAME = WinIo ws2_32 winmm mapi32 imm32 winspool comctl32 comdlg32 gdi32 ole32 user32 uuid wininet
SRC_PATH = . ./util
C_PATH = $(SRC_PATH)
CPP_PATH = $(SRC_PATH)

#DEBUG=true
include ../include.mk