/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_wizool_ctrl_InterfaceApi */

#ifndef _Included_cn_wizool_ctrl_InterfaceApi
#define _Included_cn_wizool_ctrl_InterfaceApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_wizool_ctrl_InterfaceApi
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_wizool_ctrl_InterfaceApi_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_wizool_ctrl_InterfaceApi
 * Method:    remoteOpen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_cn_wizool_ctrl_InterfaceApi_remoteOpen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     cn_wizool_ctrl_InterfaceApi
 * Method:    remoteClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_wizool_ctrl_InterfaceApi_remoteClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_wizool_ctrl_InterfaceApi
 * Method:    getTemperature
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_cn_wizool_ctrl_InterfaceApi_getTemperature
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_wizool_ctrl_InterfaceApi
 * Method:    getHumidity
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_cn_wizool_ctrl_InterfaceApi_getHumidity
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_wizool_ctrl_InterfaceApi
 * Method:    setSlaveAddr
 * Signature: (ICC)F
 */
JNIEXPORT jfloat JNICALL Java_cn_wizool_ctrl_InterfaceApi_setSlaveAddr
  (JNIEnv *, jobject, jint, jchar, jchar);

#ifdef __cplusplus
}
#endif
#endif
