TARGET = telnetd.exe
LDFLAGS = -mwindows
INC_PATH = ../include
LIBS_PATH = ../libs
LIBS_NAME = ws2_32 wininet
SRC_PATH = . ./util
C_PATH = $(SRC_PATH)
CPP_PATH = $(SRC_PATH)

DEBUG=true
include ../include.mk